version: '3'

services:

  webapp:
    container_name: labs_challenge
    image: node:12
    networks:
      - frontend
    ports:
      - "80:80"
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: 80

networks:
  frontend:
